# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='bodyHTML',
            new_name='htmlBody',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='headHTML',
            new_name='htmlHead',
        ),
    ]
