# Generated by Django 2.1.7 on 2019-03-29 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20180420_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
