# Generated by Django 2.1.7 on 2019-09-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20190329_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='toggleCodeHighlight',
            field=models.BooleanField(default=False),
        ),
    ]
