# Generated by Django 2.1.7 on 2019-09-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_page_togglecodehighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='toggleCodeHighlight',
        ),
    ]
