# Generated by Django 2.1.7 on 2019-09-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180410_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='useCodeMirror',
            field=models.BooleanField(default=False),
        ),
    ]
